Setup.state as u8 and shorter keys
SHA2017-badge/micropython-esp32 pull request #101
Opened 2017-07-23 11:16 UTC by rnplus

2017-07-23 11:27 UTC, basvs commented on esp32/modules/setup.py
> +        badge.nvs_set_u8('badge', 'setup.state', 2) # Skip the sponsors
If we change the type of 'setup.state', we should support backward compatibility / conversion of old values.

2017-07-23 11:27 UTC, basvs requested changes
we cannot just change the type of a nvs key without any conversion-code.

2017-07-23 11:40 UTC, basvs commented
> badge.nvs_set_str('badge', 'setup.state', '2')

> badge.nvs_get_str('badge', 'setup.state')

'2'

> badge.nvs_get_u8('badge', 'setup.state')

(empty response; "not set")

> badge.nvs_set_u8('badge', 'setup.state', 2)

> badge.nvs_get_u8('badge', 'setup.state')

(empty response; "not set")

> badge.nvs_get_str('badge', 'setup.state')

'2'


We're not ready for type conversion yet. Working on it..

2017-07-23 13:48 UTC, basvs commented
Fixed master-branch.

When setting a key, you can now change the key type.

badge.nvs_set_str('badge', 'something', '42')
badge.nvs_get_str('badge', 'something') -> '42'
badge.nvs_get_u8('badge', 'something') -> null

badge.nvs_set_u8('badge', 'something', 42)
badge.nvs_get_str('badge', 'something') -> null
badge.nvs_get_u8('badge', 'something') -> 42

You do *not* need an explicit nvs_erase_key.

2017-07-25 21:26 UTC, annejan commented
@basvs since we are re-flashing all . . 
I think we can merge :)

2017-07-25 21:46 UTC, basvs approved these changes

2017-07-25 21:46 UTC, basvs commented
agreed

2017-07-25 22:25 UTC, merged