Exposed badge_eink_display as Python function
SHA2017-badge/micropython-esp32 pull request #156
Opened 2017-07-31 20:44 UTC by gsuberland

At the moment there's no way to display a raw image from memory, which would be useful for displaying images generated outside of uGFX or downloaded from the internet. This PR aims to expose the badge_eink_display function from badge_eink.c as a Python function.

Fair warning, I don't have a way to set up a build environment for the code right now, so this is 100% untested. I've also never worked with MicroPython before. The commit might not even compile, although I did ask some folks in the sha2017-badge IRC channel to peer review it, and they found no glaring errors.

I've put a limited test application here, it should have the same functionality as demo_greyscale_img4.c in the Firmware/main/ directory, except in Python: https://pastebin.com/BWtDmGG3

Let me know if you need more info, or just want to generally condemn me for opening untested PRs!

2017-07-31 21:07 UTC, annejan commented
I hope to be able to check this tomorrow (no working badge at the moment) 🍷

If anyone else OKs this before me, feel free to merge!

2017-08-01 12:42 UTC, raboof requested changes
Doesn't seem to link, no time to figure out why right now, sorry...

2017-08-01 12:42 UTC, raboof commented on esp32/modbadge.c
> +	int bufferSize = mp_obj_str_get_len(obj_img);
hmm:
```
LINK build/application.elf
build/modbadge.o:(.literal.badge_eink_raw_frame+0x8): undefined reference to `mp_obj_str_get_len'
build/modbadge.o: In function `badge_eink_raw_frame':
modbadge.c:(.text.badge_eink_raw_frame+0x5): undefined reference to `mp_obj_str_get_len'
Makefile:764: recipe for target 'build/application.elf' failed
```

2017-08-01 16:08 UTC, gsuberland commented
Ah yes, my bad, I saw that function used in some MicroPython reference elsewhere but it appears to not be defined at all within the SHA badge code. It seems the only way to check the length of the string passed here is strlen, but obviously that's no use because there will be null bytes.

As a workaround I've removed the check so that this will link. People using the API will have to take care to send exactly the right length of data to the function, otherwise it'll run into UB.

2017-08-01 19:12 UTC, raboof commented
Unchecked buffers, because that's how we roll for a hacker camp badge :joy: :+1:

2017-08-01 20:19 UTC, raboof commented
Hmm I can't seem to run that test:
```
MicroPython v1.9.1-1078-g46583bf5 on 2017-08-01; SHA2017-Badge with ESP32
Type "help()" for more information.
>>> import foo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
MemoryError: memory allocation failed, allocating 2688 bytes
>>>
```

2017-08-01 22:16 UTC, basvs commented
two things:

- i'd like to enforce the use of bytestrings. (see leds_send_data for an example where we were too late; that's why it's only a warning)
- and enforce the length. Is you use the get_data instead of the get_str, you will receive the length. The length should be at least 296*128/8 bytes for 1bit images and 296*128 bytes for 8 bit images.

Btw, I split the badge_eink_display(). For greyscale you will need the badge_eink_display_greyscale(). So we might need two hooks.

2017-08-01 22:18 UTC, basvs commented
@gsuberland can you update your pull request? I can do it as well, but it takes me a bit more time..

2017-08-03 15:49 UTC, basvs commented
@gsuberland I've written this pull request, based on yours:
https://github.com/SHA2017-badge/micropython-esp32/pull/179

2017-08-04 11:19 UTC, annejan commented
Merged #179

2017-08-04 11:19 UTC, closed without merging